---
- name: Install DSpace 8.1
  hosts: hosts
  become: yes

  tasks:
    - name: Ensure wget is installed
      apt:
        name: wget
        state: present

    - name: Download DSpace 8.1 source code
      ansible.builtin.get_url:
        url: https://github.com/DSpace/DSpace/archive/refs/tags/dspace-8.1.tar.gz
        dest: /opt/dspace-8.1.tar.gz
        mode: '0644'

    - name: Extract DSpace 8.1 source code
      ansible.builtin.unarchive:
        src: /opt/dspace-8.1.tar.gz
        dest: /opt
        remote_src: yes

    - name: Create initial local.cfg from the example
      ansible.builtin.copy:
        src: /opt/DSpace-dspace-8.1/dspace/config/local.cfg.EXAMPLE
        dest: /opt/DSpace-dspace-8.1/dspace/config/local.cfg
        remote_src: yes

    - name: Create /dspace directory and assign ownership to tomcat
      ansible.builtin.file:
        path: /dspace
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0775'

    - name: Change directory to dspace-source and package using Maven
      ansible.builtin.shell: |
        cd /opt/DSpace-dspace-8.1
        sudo mvn package
      args:
        chdir: /opt/DSpace-dspace-8.1
      become: true

    - name: Install DSpace using Ant fresh_install
      ansible.builtin.shell: |
        cd /opt/DSpace-dspace-8.1/dspace/target/dspace-installer
        sudo ant fresh_install
      args:
        chdir: /opt/DSpace-dspace-8.1/dspace/target/dspace-installer
      become: true

    - name: Initialize DSpace database
      ansible.builtin.shell: |
        cd /dspace/bin
        sudo ./dspace database migrate
      args:
        chdir: /dspace/bin
      become: true

    # - name: Create DSpace admin account
    #   ansible.builtin.shell: |
    #     cd /dspace/bin
    #     sudo ./dspace create-administrator
    #   args:
    #     chdir: /dspace/bin
    #   become: true
    
    - name: Copy Solr cores to Solr configsets directory
      ansible.builtin.copy:
        src: "/dspace/solr/"
        dest: "/opt/solr8/server/solr/configsets"
        owner: dspace
        group: dspace
        mode: '0775'
        remote_src: yes
      become: true

    - name: Change ownership of the Solr configsets directory
      ansible.builtin.file:
        path: "/opt/solr/server/solr/configsets"
        owner: dspace
        group: dspace
        recurse: yes
      become: true

    - name: Restart Solr service
      ansible.builtin.shell: "./solr restart -force"
      args:
        chdir: /opt/solr8/bin
      become: true
      
    - name: Run the DSpace backend SpringBoot application
      ansible.builtin.shell: |
        nohup java -jar /dspace/webapps/server-boot.jar > /dspace/logs/server-boot.log 2>&1 &
      args:
        chdir: /dspace/webapps
      become: true

    - name: Wait for server-boot to start up (grace period)
      ansible.builtin.pause:
        seconds: 30
      when: server_boot_start_wait | default(true)
